Adding github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,20 +67,46 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
       - name: Update Lambda function
-        run: |
-          aws lambda update-function-configuration \
-            --function-name lambda-ms-demo-dev \
-            --environment "Variables={REGION=$REGION}"
-
-          aws lambda update-function-code \
-            --function-name lambda-ms-demo-dev \
-            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         env:
           AWS_REGION: ${{ vars.AWS_REGION }}
           ECR_REGISTRY: 306157427831.dkr.ecr.us-east-1.amazonaws.com
           ECR_REPOSITORY: ${{ github.event.repository.name }}
-          IMAGE_TAG: ${{ steps.short.outputs.short_sha }} 
+          IMAGE_TAG: ${{ steps.short.outputs.short_sha }}
           REGION: ${{ vars.AWS_REGION }}
+        run: |
+          FUNCTION_NAME=lambda-ms-demo-dev
+
+          # Actualizar variables de entorno
+          aws lambda update-function-configuration \
+            --function-name $FUNCTION_NAME \
+            --environment "Variables={REGION=$REGION}"
+
+          echo "Esperando que termine la actualización de variables..."
+
+          # Esperar hasta que la actualización sea exitosa
+          while true; do
+            STATUS=$(aws lambda get-function-configuration \
+              --function-name $FUNCTION_NAME \
+              --query LastUpdateStatus --output text)
+            echo "Estado actual: $STATUS"
+
+            if [ "$STATUS" == "Successful" ]; then
+              echo "Actualización de variables completada."
+              break
+            elif [ "$STATUS" == "Failed" ]; then
+              echo "Error: la actualización de variables falló."
+              exit 1
+            else
+              echo "Esperando 5 segundos..."
+              sleep 5
+            fi
+          done
+
+          # Actualizar código (imagen container)
+          aws lambda update-function-code \
+            --function-name $FUNCTION_NAME \
+            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
 
   approval-qa:
     environment:
